@gateway = https://api-gateway.happypond-6af05007.australiaeast.azurecontainerapps.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbGluaWNhX2FkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImNsaW5pY2FfYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiZXhwIjoxNzg4OTI0NDEwLCJpc3MiOiJDbGluaWNhLk9BdXRoSldUIiwiYXVkIjoiQ2xpbmljYS5DbGllbnRlcyJ9.DAwaC_6t6E9y1ZUCAI-WKFsmM8QyFyuZgLZopsXFDMQ
@pacienteId = 10
@historialId = 1

### Obtener token JWT (servicio independiente OAuthJWT)
POST {{gateway}}/oauth/token
Content-Type: application/json

{
  "usuario": "clinica_admin",
  "contrasena": "A6@wL8!qT3#yM5$v"
}

### Estado del gateway
GET {{gateway}}/health

### Crear paciente
POST {{gateway}}/pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cedula": "1755844442", 
  "nombre": "Jordy",
  "apellido": "Prado",
  "direccion": "Calle 10 # 20-30"
}

### Listar pacientes
GET {{gateway}}/pacientes
Authorization: Bearer {{token}}

### Buscar paciente por id
GET {{gateway}}/pacientes/{{pacienteId}}
Authorization: Bearer {{token}}

### Actualizar paciente
PUT {{gateway}}/pacientes/{{pacienteId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cedula": "100184568524",
  "nombre": "Melissa Ibarra",
  "apellido": "García",
  "direccion": "Carrera 5 # 11-22"
}

### Crear historial clínico
POST {{gateway}}/historiales
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "idPaciente": {{pacienteId}},
  "numHistoria": "HC-0001",
  "diagnostico": "Migraña",
  "tratamiento": "Control médico y analgésico"
}

### Listar historiales
GET {{gateway}}/historiales
Authorization: Bearer {{token}}

### Buscar historial por id
GET {{gateway}}/historiales/{{historialId}}
Authorization: Bearer {{token}}

### Actualizar historial
PUT {{gateway}}/historiales/{{historialId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "idPaciente": {{pacienteId}},
  "numHistoria": "HC-0001",
  "diagnostico": "Migraña controlada",
  "tratamiento": "Seguimiento en 30 días"
}

### Eliminar historial
DELETE {{gateway}}/historiales/{{historialId}}
Authorization: Bearer {{token}}

### Eliminar paciente
DELETE {{gateway}}/pacientes/{{pacienteId}}
Authorization: Bearer {{token}}
